# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BG_CoffeeQuest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BG_CoffeeQuest
  pod 'YelpAPI', '3.0.0'

end
